[package]
name = "geodb"
version = "0.1.0-alpha1"
edition = "2021"
authors = ["Jian Chen <admin@chensoft.com>"]
license = "MIT"
description = "A collection of geographical information"
documentation = "https://docs.rs/geodb"
repository = "https://github.com/chensoft/geodb"
readme = "README.md"
keywords = ["geodb"]

[[bench]]
name = "bench"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.5"
